### ISSUE TITLE
No definition about variable 'activations' used for getting heatmap and mask

### ISSUE THREAD

**Issue by msra-jqxu** [opanhw/MM_Neurons#1]
Hi, I noticed that the variable 'activations' doesn't seem to be defined [here](https://github.com/opanhw/MM_Neurons/blob/53746c1c610a4d2ccae9cc47322a685746b48122/src/trainer.py#L497C26-L497C37). Could you update the code? Thanks!

**Comment by opanhw** [comment]
Thank you for raising this issue. I have updated the `trainer.py` file. Please check if it works now.

**Comment by msra-jqxu** [comment]
Thanks! It works for me.

What's more, I'm curious why there is an img_tensor in addition to image_tensor [here](https://github.com/opanhw/MM_Neurons/blob/ca6cbdc63ea6509198c12023e49ad93bb89092f2/src/trainer.py#L351)? In fact, the key of self.processor.image_processor.preprocess(image, return_tensors='pt') only has 'pixel_values' but no 'pixel'.

If I use img_tensor = image_tensor, then an error will be reported when [saving ‘image.png’](https://github.com/opanhw/MM_Neurons/blob/ca6cbdc63ea6509198c12023e49ad93bb89092f2/src/trainer.py#L493) because the dimension is (3, 224, 224). After I modify img_tensor to (224, 224, 3), the saved image below does not seem correct. Do I need to normalize the img_tensor to 0-255?
![image](https://github.com/user-attachments/assets/35bf85ed-8573-4c1f-8248-d5402d98a6f5)

**Comment by opanhw** [comment]
In fact, 'img_tensor' and 'image_tensor' are not the same. The pixel key is manually added, to get image tensors before being rescaled and normalized. Please replace `transformers/models/blip/image_processing_blip.py` in your own python libary with `src/image_processing_blip.py`, a newly uploaded file.

**Comment by msra-jqxu** [comment]
Hi, @opanhw, thanks for your efforts! Now the code works fine.

However, I hope the code could be better. For example, self.args.preparation_path and self.cal_activations are not defined in src/trainer.py and open_source_model/LLaVA/llava_llama.py respectively. And some python packages are not listed in requirements.txt. I spent some effort to fix them while running the code.

Thanks again！
