### ISSUE TITLE
A question about equation2 in the paper.

### ISSUE THREAD

**Issue by bdne** [opanhw/MM_Neurons#2]
Thanks for the nice work! I have a question about the $h_{-1}^{L-1}$ in equation2. It seems that it could be removed because there is no residual connection between output from the previous layer and the last layer.

**Comment by opanhw** [comment]
Hi, I couldn't find $h_{-1}^{L-1}$ in equation 2, are you trying to say the equation 3? But it couldn't be removed, since each layer has residual connection, as well as the last layer.

**Comment by bdne** [comment]
Each layer contains only two residual connections, one is in FFN ，and another one is in self attention. And it seems there are no direct connections from one layer to the next. I’m not sure if I understand this correctly.

**Comment by opanhw** [comment]
The following code in LLaMA may help you understand the residual stream more easily.
```
residual = hidden_states

hidden_states = self.input_layernorm(hidden_states)

# Self Attention
hidden_states, self_attn_weights, present_key_value = self.self_attn(
    hidden_states=hidden_states,
    attention_mask=attention_mask,
    position_ids=position_ids,
    past_key_value=past_key_value,
    output_attentions=output_attentions,
    use_cache=use_cache,
)
hidden_states = residual + hidden_states

# Fully Connected
residual = hidden_states
hidden_states = self.post_attention_layernorm(hidden_states)
hidden_states = self.mlp(hidden_states)
hidden_states = residual + hidden_states

outputs = (hidden_states,)
```
And we omit the layernorm in the equation.

**Comment by bdne** [comment]
Thanks! I understand!
